config/routes.rb
WorkerInfo::Application.routes.draw do

  root :to => 'participants#new'

  resources :twitter_checks

  resources :participants do
    resources :values
    resources :users
    resources :personalities    
    resources :demographics
    resources :article_ratings
    
    resources :article_ratings do
      resources :article_content_ratings
    end
  end
  
  
  match "/auth/:provider/callback" => "sessions#create"

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  # attr_accessible :title, :body
  has_one :personalities
  has_one :demographics
  has_many :article_ratings
#  has_many :article_content_ratings
  has_one :values

  validates_presence_of :condition

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  protect_from_forgery :except => [:new, :create, :index, :show]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @participants }
    end
  end

  def show
    @participant = Participant.find(params[:id])
  end


  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new


    @participant.assignment_id = params[:assignmentId]
    @participant.hit_id = params[:hitId]
    @participant.worker_id = params[:workerId]
    @participant.article_type_id_array = request.remote_ip

    @participant_old = Participant.find(:first, :conditions => [ "worker_id = ? AND id < 819", @participant.worker_id])


    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @participant }
    end
  end


  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(params[:participant])
    

    
    @participant_old = Participant.find(:first, :conditions => [ "worker_id = ? AND id < 906", @participant.worker_id])
#    if @participant_old != nil
#      @participant_old.condition = @participant.condition
#      @participant = @participant_old.dup
#    end

    if @participant.save

      ##uncomment for live
      #redirect_to('https://www.mturk.com/mturk/externalSubmit?condition='+@participant.condition.to_s+'&id='+@participant.id.to_s+'&assignmentId=' + @participant.assignment_id)
      
      ##uncomment for sandbox
      #redirect_to('https://workersandbox.mturk.com/mturk/externalSubmit?condition='+@participant.condition.to_s+'&id='+@participant.id.to_s+'&assignmentId=' + @participant.assignment_id)

      #redirect_to('https://www.mturk.com/mturk/externalSubmit?condition='+@participant.condition.to_s+'&participantId='+@participant.id.to_s+'&assignmentId='+@participant.assignment_id.to_s+'&hitId='+@participant.hit_id.to_s+'&workerId='+@participant.worker_id.to_s+'') 
      #format.json { render :json => @participant, :status => :created, :location => @participant }

      redirect_to(participant_path(@participant.id)) 

    else
      render :action => "new" 
    end


#    else


#      article_type_id_array=(1..3).to_a
#      article_type_id_array = article_type_id_array.sort_by { rand }

#      article_within_type_id_array=[rand(3)+1,rand(3)+1,rand(3)+1]

#      @participant.article_type_id_array = article_type_id_array.join(",")
#      @participant.article_within_type_id_array = article_within_type_id_array.join(",")
#    end
    


  end

end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= simple_form_for(@participant) do |f| %>
  <%= f.error_notification %>


  <%= f.hidden_field :worker_id %>
  <%= f.hidden_field :hit_id %>
  <%= f.hidden_field :assignment_id %>
  <%= f.hidden_field :article_type_id_array %>

	<% if @participant.worker_id != nil and @participant.worker_id != ""  %>


		<p>To complete the HIT, please:</p>

		<p>1. Begin and complete the survey. </p>

		<%= link_to 'Click Here To Complete Survey', new_twitter_check_path(:worker_id=>@participant.worker_id,:hit_id=>@participant.hit_id,:assignment_id=>@participant.assignment_id), :target => '_blank', :style=>"font-size:20px;" %>

		<br><br><br>

		<p>2. Enter in the secret code you receive from completing the survey below, and then submit the HIT. Your work will be rejected if the code does not match with the one you get from completing the HIT</p>

		<p><%=f.input :condition, :label=>"Enter your code below"%></p>

		<%= f.submit "Commit HIT" , :class => 'btn btn-primary'  %>

		<br>



	<% else %>
		*You must accept HIT to continue.<br>
	<% end %>

<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Thank you</h1>

We are submitting your HIT right now...


<script type="text/javascript">

window.location = 'https://www.mturk.com/mturk/externalSubmit?assignmentId=<%=@participant.assignment_id.to_s%>&cond=1'

</script>

app/views/participants/new.html.erb
<h2>Consent Form</h2>

		<% if @participant.worker_id != nil and @participant.worker_id != "" and @participant_old != nil %>

		<p>We are seeking individuals who have <b>not</b> completed our Twitter News Survey to participate in this study. </p>
		<p>Our records indicate that you have completed the Twitter News Survey previously. If this is an error, please contact <a href="mailto:garyhsieh@gmail.com">garyhsieh@gmail.com</a>. Thank you!</p>

		<% else %>

		<p>You have been invited to participate in this research study to help us examine Twitter Users' value orientations. </p><br>
		
		<p>In order to participate in this study, you must meet the following requirements:<br> 
		<ol>
			<li>Have a Twitter account</li>
			<li>Have *not* participated in our previous TWITTER NEWS STUDY</li>
		</ol></p><br>

		<p>If you agree to participate, you will be asked to click the link below to complete an online survey. Your participation would <b>take about ten minutes</b>. You are free to withdraw your consent and to discontinue participation at any time. You must be <b>18 or older to participate</b>. In exchange for your participation, you will <b>receive $0.75</b>. This research study will not involve any cost for you.</p><br> 

		<p>Your privacy will be protected to the maximum extent allowable by law. Your answers are completely confidential and your name will not be linked to the data in any way. This survey is completely voluntary; you can stop at any time or not answer any questions that you are uncomfortable with.</p><br>

		<p>This research is being conducted through the Department of Communications at Michigan State University. If you have any questions or comments regarding this study, you can contact Professor Gary Hsieh, 517-355-9734 or garyhsieh@gmail.com</p><br>

		<p>If you have any questions or concerns about your role and rights as a research participant, or would like to register a complaint about this study, you may contact, anonymously if you wish, the MSU’s Human Research Protection Program, at 517-355-2180, Fax 517-432-4503, or e-mail irb@msu.edu or regular mail at 207 Olds Hall, MSU, East Lansing, MI 48824.</p><br>

		<br>

		<p><i>By continuing, you are agreeing to the above terms.</i></p><br>

		<hr>

		<%= render 'form' %>
		
		<% end %>

app/views/participants/show.html.erb
<h1>Thank you</h1>
<br>
<h3>We are submitting your HIT right now...</h3>


<script type="text/javascript">
	window.location = 'https://www.mturk.com/mturk/externalSubmit?assignmentId=<%=@participant.assignment_id.to_s%>&cond=1'
</script>