config/routes.rb
WorkerInfo::Application.routes.draw do

  root :to => 'participants#new'

  resources :twitter_checks

  resources :participants do
    resources :values
    resources :users
    resources :personalities    
    resources :demographics
    resources :article_ratings
    
    resources :article_ratings do
      resources :article_content_ratings
    end
  end
  
  
  match "/auth/:provider/callback" => "sessions#create"

end

app/models/article_rating.rb
class ArticleRating < ActiveRecord::Base
  belongs_to :participant
  has_one :article_content_rating
  validates_presence_of :rating_01
  
end

app/controllers/article_ratings_controller.rb
class ArticleRatingsController < ApplicationController
  before_filter :get_participant
  protect_from_forgery :except => [:new, :create, :index]

  # GET /article_ratings
  # GET /article_ratings.json
  def index
    @article_ratings = ArticleRating.all

    @articleRatings_old = ArticleRating.find(:all, :conditions => [ "participant_id = ?", @participant.id], :group => 'article_id')
    
    if @articleRatings_old != nil and @articleRatings_old.size >= 2
      redirect_to new_participant_demographic_path(@participant)

    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @article_ratings }
      end
    end

  end

  # GET /article_ratings/new
  # GET /article_ratings/new.json
  def new
    @article_rating = ArticleRating.new
    
    #need to calculate position
    
#    position = 0
    
    @articleRatings_old = ArticleRating.find(:all, :conditions => [ "participant_id = ?", @participant.id], :group => 'article_id')
    
    if @articleRatings_old != nil
      @position = @articleRatings_old.size      
    else
      @position = 0
    end

    
##    
      
      @articleContentRatings_old = ArticleContentRating.find(:all, :conditions => [ "participant_id = ?", @participant.id], :group => 'article_id')
      
        
      if @articleRatings_old != nil and @articleRatings_old.size >= 2
        redirect_to new_participant_demographic_path(@participant)
      
      elsif @position == @articleContentRatings_old.size
            article_within_type_id_array=@participant.article_within_type_id_array.split(",").map(&:to_i)
            article_type_id_array=@participant.article_type_id_array.split(",").map(&:to_i)
            @article = Article.find(:first, :conditions => [ "within_type_id = ? AND type_id=?", article_within_type_id_array[@position],article_type_id_array[@position]])
        #    @article = Article.where("within_type_id=? AND type_id=?",1, 1)  
        #    @article = Article.find(1)      

            @article_rating.article_id = @article.id

            respond_to do |format|
              format.html # new.html.erb
              format.json { render :json => @article_rating }
            end        
      else
        redirect_to new_participant_article_rating_article_content_rating_path(@participant, @articleRatings_old.first)   
      end  

  end

  # POST /article_ratings
  # POST /article_ratings.json
  def create
    @article_rating = ArticleRating.new(params[:article_rating])
    @article_rating.participant_id = @participant.id


    respond_to do |format|
      if @article_rating.save
        format.html { redirect_to new_participant_article_rating_article_content_rating_path(@participant, @article_rating) }
#        format.html { redirect_to new_participant_article_content_rating_path(@participant) }
        format.json { render :json => @article_rating, :status => :created, :location => @article_rating }
      else
        @article = Article.find(@article_rating.article_id)
        @articleRatings_old = ArticleRating.find(:all, :conditions => [ "participant_id = ?", @participant.id], :group => 'article_id')

        if @articleRatings_old != nil
          @position = @articleRatings_old.size      
        else
          @position = 0
        end
        format.html { render :action => "new" }
        format.json { render :json => @article_rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /article_ratings/1
  # PUT /article_ratings/1.json
  def update
    @article_rating = ArticleRating.find(params[:id])

    respond_to do |format|
      if @article_rating.update_attributes(params[:article_rating])
        format.html { redirect_to @article_rating }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article_rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  private
                    
    def get_participant
      @participant = Participant.find(:first, :conditions => [ "id = ?", params[:participant_id]])
    end
end

app/helpers/article_ratings_helper.rb
module ArticleRatingsHelper
end

app/views/article_ratings/_form.html.erb
<%= simple_form_for([@participant,@article_rating]) do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
	<br>
	<p>Imagine you just received the following tweet in your feed:</p>
	<p><p><img src="../../../../../images/<%=@article.tweet_path%>"> </P></p>	
	
	<%= f.hidden_field :article_id %>
	<b>
		<br>
	<%= f.input :rating_01, :label=>"<b>After reading the tweet, how likely to click to read this article?</b>", :collection => [['1 - Extremely unlikely',1],["2 - Unlikely",2],["3 - Neutral",3],["4 - Likely",4],["5 - Extremely likely",5]], :as => :radio%>		
	
	<br>

  </div>

  <div class="actions">
    <br><%= f.submit "To Article" , :class => 'btn btn-primary'  %>
  </div>
<% end %>

app/views/article_ratings/edit.html.erb
<h1>Editing article_rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @article_rating %> |
<%= link_to 'Back', article_ratings_path %>

app/views/article_ratings/index.html.erb
<h2>Instructions</h2>

<p>In the next section, you are presented with a series of 2 articles. Imagine these are articles shared with you via your social network streams, e.g., Twitter.</p>	

<p>Look over the title of the articles and decide if they are something you would be interested in reading. Then read the articles and tell us what you think about them.</p>	

<p>Note: these are articles from <a href="http://lifehacker.com/" target="blank">LifeHacker</a> that have been shared on Twitter in the past. LifeHacker is a popular internet blog about life hacks (tricks, skills or methods that solves an everyday problem in a clever or non-obvious way).</p>


	
	<br>

<%= link_to 'Rate Articles', new_participant_article_rating_path, :class => 'btn btn-primary'  %>

app/views/article_ratings/new.html.erb
<h2>Article Rating #<%=@position+1%></h2>

<%= render 'form' %>

app/views/article_ratings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_article_rating_path(@article_rating) %> |
<%= link_to 'Back', article_ratings_path %>