config/routes.rb
WorkerInfo::Application.routes.draw do

  root :to => 'participants#new'

  resources :twitter_checks

  resources :participants do
    resources :values
    resources :users
    resources :personalities    
    resources :demographics
    resources :article_ratings
    
    resources :article_ratings do
      resources :article_content_ratings
    end
  end
  
  
  match "/auth/:provider/callback" => "sessions#create"

end

app/models/twitter_check.rb
class TwitterCheck < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/twitter_checks_controller.rb
class TwitterChecksController < ApplicationController
#  before_filter :get_participant
  protect_from_forgery :except => [:new, :create, :index]


  # GET /twitter_checks/new
  # GET /twitter_checks/new.json
  def new
    @twitter_check = TwitterCheck.new

    @participant = Participant.new
    @participant.assignment_id = params[:assignmentId]
    @participant.hit_id = params[:hitId]
    @participant.worker_id = params[:workerId]
    @participant.condition = request.remote_ip.gsub '.',''


    @participant_old = Participant.find(:first, :conditions => [ "worker_id = ?", @participant.worker_id])
    if @participant.worker_id != "" && @participant_old != nil
      @participant = @participant_old
    else
      article_type_id_array=(4..5).to_a
      article_type_id_array = article_type_id_array.sort_by { rand }

      article_within_type_id_array=[rand(3)+1,rand(3)+1]

      @participant.article_type_id_array = article_type_id_array.join(",")
      @participant.article_within_type_id_array = article_within_type_id_array.join(",")
    end

    @participant.save

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @twitter_check }
    end
  end


  # POST /twitter_checks
  # POST /twitter_checks.json
  def create
##    @twitter_check = TwitterCheck.new(params[:twitter_check])

    @participant = Participant.find(params[:twitter_check][:participant_id])

    if @participant != nil
      redirect_to new_participant_personality_path(@participant) 
    else
      render :action => "new"
    end
  end

  
  
 # private
 #                   
 #   def get_participant
 #     @participant = Participant.find(:first, :conditions => [ "id = ?", params[:participant_id]])
 #   end
end

app/helpers/twitter_checks_helper.rb
module TwitterChecksHelper
end

app/views/twitter_checks/_form.html.erb
<%= simple_form_for(@twitter_check) do |f| %>
  <%= f.error_notification %>

  <%= f.hidden_field "participant_id", :value => @participant.id %>

  <div class="actions">
    <br><%= f.submit "Continue" , :class => 'btn btn-primary'  %>
  </div>

<% end %>

app/views/twitter_checks/edit.html.erb
<h1>Editing twitter_check</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter_check %> |
<%= link_to 'Back', twitter_checks_path %>

app/views/twitter_checks/index.html.erb
<h1>Listing twitter_checks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @twitter_checks.each do |twitter_check| %>
  <tr>
    <td><%= link_to 'Show', twitter_check %></td>
    <td><%= link_to 'Edit', edit_twitter_check_path(twitter_check) %></td>
    <td><%= link_to 'Destroy', twitter_check, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Twitter check', new_twitter_check_path %>

app/views/twitter_checks/new.html.erb
<h2>Checking Participation Qualification</h2>

<p>You will be asked a series of questions about yourself. You will then be asked to assess some articles that you may see on Twitter.</p>

<%= render 'form' %>

app/views/twitter_checks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_twitter_check_path(@twitter_check) %> |
<%= link_to 'Back', twitter_checks_path %>