config/routes.rb
WorkerInfo::Application.routes.draw do

  root :to => 'participants#new'

  resources :twitter_checks

  resources :participants do
    resources :values
    resources :users
    resources :personalities    
    resources :demographics
    resources :article_ratings
    
    resources :article_ratings do
      resources :article_content_ratings
    end
  end
  
  
  match "/auth/:provider/callback" => "sessions#create"

end

app/models/article_content_rating.rb
class ArticleContentRating < ActiveRecord::Base
  belongs_to :article_rating
  validates_presence_of :tag_01,:tag_02,:tag_03,:rating_01,:rating_02

end

app/controllers/article_content_ratings_controller.rb
class ArticleContentRatingsController < ApplicationController
  before_filter :get_participant
  protect_from_forgery :except => [:new, :create, :index]
  
  # GET /article_content_ratings
  # GET /article_content_ratings.json
  def index
    @article_content_ratings = ArticleContentRating.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @article_content_ratings }
    end
  end


  # GET /article_content_ratings/new
  # GET /article_content_ratings/new.json
  def new
    @article_content_rating = ArticleContentRating.new
    @article_rating = ArticleRating.find(params[:article_rating_id])
    @article = Article.find(@article_rating.article_id)
    @article_content_rating.article_id = @article.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @article_content_rating }
    end
  end

  # POST /article_content_ratings
  # POST /article_content_ratings.json
  def create
    @article_content_rating = ArticleContentRating.new(params[:article_content_rating])
    @article_content_rating.participant_id = @participant.id

    @article_rating = ArticleRating.find(params[:article_rating_id])
    @article = Article.find(@article_rating.article_id)

    @article_content_ratings_old = ArticleContentRating.find(:all, :conditions => [ "participant_id = ?", @participant.id], :group => 'article_id')

    if @article_content_ratings_old != nil and @article_content_ratings_old.size >= 2
          respond_to do |format|
            if @article_content_rating.save
              format.html { redirect_to new_participant_demographic_path(@participant) }
      #        format.html { redirect_to new_participant_demographic_path(@participant) }
              format.json { render :json => @article_content_rating, :status => :created, :location => @article_content_rating }
            else
              format.html { render :action => "new" }
              format.json { render :json => @article_content_rating.errors, :status => :unprocessable_entity }
            end
          end      
    else
        respond_to do |format|
          if @article_content_rating.save
            format.html { redirect_to new_participant_article_rating_path(@participant) }
    #        format.html { redirect_to new_participant_demographic_path(@participant) }
            format.json { render :json => @article_content_rating, :status => :created, :location => @article_content_rating }
          else
            @article = Article.find(@article_content_rating.article_id)     
            format.html { render :action => "new" }
            format.json { render :json => @article_content_rating.errors, :status => :unprocessable_entity }
          end
        end
    end
    
  end

  # PUT /article_content_ratings/1
  # PUT /article_content_ratings/1.json
  def update
    @article_content_rating = ArticleContentRating.find(params[:id])

    respond_to do |format|
      if @article_content_rating.update_attributes(params[:article_content_rating])
        format.html { redirect_to @article_content_rating, :notice => 'Article content rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article_content_rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  private
                    
    def get_participant
      @participant = Participant.find(:first, :conditions => [ "id = ?", params[:participant_id]])
      @article_rating = ArticleRating.find(:first, :conditions => [ "id = ?", params[:article_rating_id]])

    end
end

app/helpers/article_content_ratings_helper.rb
module ArticleContentRatingsHelper
end

app/views/article_content_ratings/_form.html.erb
<%= simple_form_for([@participant,@article_rating,@article_content_rating]) do |f| %>

  <%= f.error_notification %>

	
	<p><img src="../../../../../images/<%=@article.content_path%>"> </P>
	

	<hr>
	<h4>Please answer some questions about the article</h4>
	<p>Please provide three keywords to help categorize the above article:</p>
<%= f.input :tag_01, :label=>false%>
<%= f.input :tag_02, :label=>false%>
<%= f.input :tag_03, :label=>false%>

		<br>
		
		<p>To what degree do you agree with the following statements:</p>
	
<%= f.input :rating_01, :label=>"<b>I found the article to be worth reading.</b>", :collection => [['1 - Strongly disagree',1],["2 - Disagree",2],["3 - Neither disagree nor agree",3],["4 - Agree",4],["5 - Strongly agree",5]], :as => :radio%>	

		<br>
	
<%= f.input :rating_02, :label=>"<b>I would retweet the article.</b>", :collection => [['1 - Strongly disagree',1],["2 - Disagree",2],["3 - Neither disagree nor agree",3],["4 - Agree",4],["5 - Strongly agree",5]], :as => :radio%>		
	

  <div class="actions">
		<%= f.hidden_field :article_id %>
    <br><%= f.submit "Continue" , :class => 'btn btn-primary'  %>
  </div>
<% end %>

app/views/article_content_ratings/edit.html.erb
<h1>Editing article_content_rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @article_content_rating %> |
<%= link_to 'Back', article_content_ratings_path %>

app/views/article_content_ratings/index.html.erb
<h1>Listing article_content_ratings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @article_content_ratings.each do |article_content_rating| %>
  <tr>
    <td><%= link_to 'Show', article_content_rating %></td>
    <td><%= link_to 'Edit', edit_article_content_rating_path(article_content_rating) %></td>
    <td><%= link_to 'Destroy', article_content_rating, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article content rating', new_article_content_rating_path %>

app/views/article_content_ratings/new.html.erb
<h3>Read the Article</h3>

<%= render 'form' %>

app/views/article_content_ratings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_article_content_rating_path(@article_content_rating) %> |
<%= link_to 'Back', article_content_ratings_path %>